### PR TITLE
few updates

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Review by ggoffy — COMMENTED** [review]
in changelotg.txt you wrote: "add |default:null to <{foreach (mamba)"
but there is no template where it is done

**Comment by mambax7** [comment]
I reversed the direct commit here, because I wanted to have the changes as a PR that you could approve, and now somehow it doesn't include them. I'll need to take a look to see what is going on.

**Comment by mambax7** [comment]
OK, it should be now there. Let me know if it makes sense for you.

**Review by ggoffy — APPROVED** [review]

**Comment by ggoffy** [comment]
thank you

**Pull request merged**
